euler148_mt: euler148_mt.c
	gcc euler148_mt.c -o euler148_mt -I../../async -L../../async -lasync

euler148_mt_d: euler148_mt.c
	gcc -g euler148_mt.c -o euler148_mt_d -I../../async -L../../async -lasync_d

euler148_mt2: euler148_mt2.c
	gcc euler148_mt.c -o euler148_mt2 -I../../async -L../../async -lasync

euler148_mt2_d: euler148_mt2.c
	gcc -g euler148_mt2.c -o euler148_mt2_d -I../../async -L../../async -lasync_d